### ISSUE TITLE
As an app I need a Create Categories screen for my organisation 

### ISSUE THREAD

**Issue by hshayesteh** [dambileh/Abblar#13]
This will simply list different categories of messages (channels) that the user can subscribe to. We probably need some sort of a list with a checkbox next to each item.

Just to give you an idea, take Telkom as an example, it could have "Fault report", "Promotions" and etc categories

**Comment by dambileh** [comment]
![awrdp](https://cloud.githubusercontent.com/assets/9001081/6324986/26e2081c-bb4a-11e4-8932-df42e831dbfd.png)

**Comment by hshayesteh** [comment]
![list_mail](https://cloud.githubusercontent.com/assets/9001081/6325003/57dd1c86-bb4a-11e4-9caf-1725cd37d80a.png)
